# Generated by Django 5.2.8 on 2025-11-21 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="O Biurze ATBalance",
                        max_length=200,
                        verbose_name="Tytuł",
                    ),
                ),
                ("description", models.TextField(verbose_name="Opis")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Sekcja O nas",
                "verbose_name_plural": "Sekcja O nas",
            },
        ),
        migrations.CreateModel(
            name="Advantage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="np. FaMedal, FaUserCheck",
                        max_length=50,
                        verbose_name="Ikona (nazwa React Icons)",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tytuł")),
                ("description", models.TextField(verbose_name="Opis")),
                ("order", models.IntegerField(default=0, verbose_name="Kolejność")),
            ],
            options={
                "verbose_name": "Przewaga",
                "verbose_name_plural": "Przewagi (Dlaczego my)",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                ("address", models.TextField(verbose_name="Adres")),
                (
                    "working_hours",
                    models.CharField(
                        default="Pn-Pt: 9:00-17:00",
                        max_length=100,
                        verbose_name="Godziny pracy",
                    ),
                ),
                (
                    "map_lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Szerokość geograficzna",
                    ),
                ),
                (
                    "map_lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Długość geograficzna",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Informacje kontaktowe",
                "verbose_name_plural": "Informacje kontaktowe",
            },
        ),
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Imię i nazwisko"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                ("message", models.TextField(verbose_name="Wiadomość")),
                (
                    "consent",
                    models.BooleanField(
                        default=False, verbose_name="Zgoda na przetwarzanie danych"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="Adres IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data utworzenia"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Przeczytane"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notatki (wewnętrzne)"),
                ),
            ],
            options={
                "verbose_name": "Zgłoszenie kontaktowe",
                "verbose_name_plural": "Zgłoszenia kontaktowe",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Profesjonalne Usługi Księgowe",
                        max_length=200,
                        verbose_name="Tytuł",
                    ),
                ),
                (
                    "subtitle",
                    models.TextField(
                        default="Zajmiemy się Twoją księgowością - Ty zajmij się rozwojem firmy.",
                        verbose_name="Podtytuł",
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        default="Skontaktuj się z nami",
                        max_length=100,
                        verbose_name="Tekst przycisku CTA",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="hero/",
                        verbose_name="Obrazek tła",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Sekcja Hero",
                "verbose_name_plural": "Sekcja Hero",
            },
        ),
        migrations.CreateModel(
            name="SEOSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        default="Biuro Rachunkowe ATBalance - Profesjonalne Usługi Księgowe",
                        max_length=70,
                        verbose_name="Meta Title",
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        default="Kompleksowa obsługa księgowa dla firm. Księgowość, kadry, płace, ZUS, deklaracje podatkowe.",
                        max_length=160,
                        verbose_name="Meta Description",
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        default="biuro rachunkowe, księgowość, usługi księgowe, rozliczenia ZUS",
                        max_length=255,
                        verbose_name="Meta Keywords",
                    ),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/",
                        verbose_name="Open Graph Image",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywny"),
                ),
            ],
            options={
                "verbose_name": "Ustawienia SEO",
                "verbose_name_plural": "Ustawienia SEO",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="np. FaBook, FaCalculator",
                        max_length=50,
                        verbose_name="Ikona (nazwa React Icons)",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Nazwa usługi"),
                ),
                ("description", models.TextField(verbose_name="Opis usługi")),
                ("order", models.IntegerField(default=0, verbose_name="Kolejność")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktywna"),
                ),
            ],
            options={
                "verbose_name": "Usługa",
                "verbose_name_plural": "Usługi",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Value",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        help_text="np. FaTrophy, FaCheckCircle",
                        max_length=50,
                        verbose_name="Ikona (nazwa React Icons)",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Tytuł")),
                ("description", models.TextField(verbose_name="Opis")),
                ("order", models.IntegerField(default=0, verbose_name="Kolejność")),
            ],
            options={
                "verbose_name": "Wartość",
                "verbose_name_plural": "Wartości",
                "ordering": ["order"],
            },
        ),
    ]
